# .github/workflows/transliterate.yml
name: Transliterate files

on:
  push:
    paths: 
      - "files/input/**"
      - "src/**"
      - "Makefile"

jobs:
  transliterate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          make clean
          make

      - name: Transliterate notes
        run: |
          ./build/transliterate.exe files/input files/output

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-transliterate /input files."
